import { RouterOSAPI } from 'node-routeros';
import { Router } from '@prisma/client';
import { IRouterService } from './interfaces/IRouterService';
import { decrypt } from '../utils/encryption';
import { logger } from '../utils/logger';

export class RouterService implements IRouterService {
  
  /**
   * Connexion sécurisée au routeur MikroTik
   */
  async connect(router: Router): Promise<RouterOSAPI> {
    // Déchiffrement sécurisé du mot de passe stocké en BDD
    const passwordParts = router.apiPassword.split(':');
    const decryptedPassword = decrypt({ iv: passwordParts[0], content: passwordParts[1] });

    const conn = new RouterOSAPI({
      host: router.ipAddress,
      user: router.apiUser,
      password: decryptedPassword,
      port: router.apiPort,
      timeout: 10 // secondes
    });

    try {
      await conn.connect();
      logger.info(`Connecté au routeur ${router.ipAddress}`);
      return conn;
    } catch (error: any) {
      logger.error(`Erreur connexion MikroTik ${router.ipAddress}: ${error.message}`);
      throw new Error(`Failed to connect to router: ${router.name}`);
    }
  }

  /**
   * Récupération des forfaits (User Profiles) depuis le MikroTik
   */
  async getProfiles(router: Router): Promise<any[]> {
    const conn = await this.connect(router);
    try {
      // Commande MikroTik: /ip/hotspot/user/profile/print
      const profiles = await conn.write('/ip/hotspot/user/profile/print');
      return profiles;
    } catch (error: any) {
      logger.error(`Erreur lecture profils: ${error.message}`);
      throw error;
    } finally {
      conn.close();
    }
  }

  /**
   * Création d'un ticket (Voucher) sur le MikroTik
   */
  async createVoucher(router: Router, profileName: string, voucherCode: string): Promise<boolean> {
    const conn = await this.connect(router);
    try {
      // Commande: /ip/hotspot/user/add name="CODE" password="CODE" profile="PROFILE"
      await conn.write('/ip/hotspot/user/add', [
        `=name=${voucherCode}`,
        `=password=${voucherCode}`, // Le voucher est souvent username=password
        `=profile=${profileName}`,
        `=comment=Generated by SaaS`
      ]);
      logger.info(`Voucher ${voucherCode} créé avec succès sur le routeur ${router.name}`);
      return true;
    } catch (error: any) {
      logger.error(`Échec création voucher: ${error.message}`);
      throw error;
    } finally {
      conn.close();
    }
  }

  /**
   * Suppression d'un ticket (par ex. si annulé)
   */
  async deleteVoucher(router: Router, voucherCode: string): Promise<boolean> {
    const conn = await this.connect(router);
    try {
      // Trouver l'ID interne du user
      const users = await conn.write('/ip/hotspot/user/print', [`?name=${voucherCode}`]);
      if (users.length > 0 && users[0]['.id']) {
        await conn.write('/ip/hotspot/user/remove', [`=.id=${users[0]['.id']}`]);
        logger.info(`Voucher ${voucherCode} supprimé.`);
      }
      return true;
    } catch (error: any) {
      logger.error(`Échec suppression voucher: ${error.message}`);
      throw error;
    } finally {
      conn.close();
    }
  }
}
